### ISSUE TITLE
Request: unvendor `jzon`

### ISSUE THREAD

**Issue by fosskers** [MarceColl/isen#1]
Since `jzon` is now on Ultralisp, I think it can be unvendored from this project. Incidentally, being vendored is actually creating a conflict for other users; performing `(ql:quickload :com.inuoe.jzon)` actually downloads your vendored version of it, not the true version.

Thanks!

**Comment by Zulu-Inuoe** [comment]
In https://github.com/ultralisp/ultralisp/issues/195 they added the `jzon/` dir from this project to the ignore list, so UL should now pull the new entry
